LIFECYCLE_EVENTS = {
    "VC_PIPELINE_START",
    "VC_INTENT_PARSED",
    "VC_HIVE_RETRIEVE",
    "VC_MISSION_READY",
    "VC_ROUTER_DECISION",
    "VC_ACTION_VALIDATED",
    "VC_ACTION_DISPATCHED",
    "VC_SUBGOAL_ADVANCED",
    "VC_COMPLETION_CHECK",
    "VC_MISSION_COMPLETED",
    "VC_FALLBACK_USED",
    "VC_ERROR",
}
